export { About } from './AboutPage'
export { Account } from './AccountPage'
export { Cart } from './CartPage'
export { Catalog } from './CatalogPage'
export { Checkout } from './CheckoutPage'
export { Home } from './HomePage'
export { PaymentResult } from './PaymentResultPage'
export { ProductView } from './ProductPage'
